name: Deploy Cloud Run Infra and App

on:
  push:
    branches:
      - Infra

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  CREDENTIALS: ${{ secrets.CREDENTIALS }}

jobs:
  terraform-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./
        run: terraform init

      - name: Terraform Validate
        working-directory: ./
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./
        env:
          var.project_id: ${{ secrets.GCP_PROJECT_ID }}
          var.region: ${{ secrets.GCP_REGION }}
          var.credentials: ${{ secrets.CREDENTIALS }}
          var.image: ${{ secrets.IMAGE_NAME }}
          var.service_account_email: "${{ secrets.GCP_SA_EMAIL }}"
          var.service_name: "${{ secrets.SERVICE_NAME }}"
        run: terraform plan -out=tfplan
        

      - name: Terraform Apply
        working-directory: ./
        run: terraform apply -auto-approve tfplan

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" \
            --region="${{ env.REGION }}" \
            --platform=managed \
            --allow-unauthenticated
